server:
  port: 8081

knife4j:
  enable: true
  production: false
  cors: false
  basic:
    enable: true
    username: test
    password: 12313
  documents:
    -
      group: 2.0
      name: 其他文档
      locations: classpath:markdown/*
    -
      group: 1.2.x
      name: 接口签名
      locations: classpath:markdown/sign.md
  setting:
    language: zh-CN
    enableSwaggerModels: false
    enableDocumentManage: true
    enableVersion: false
    enableReloadCacheParameter: true
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: false
    enableRequestCache: false
    enableHost: false
    enableHostText: 192.168.0.193:8000
    enableHomeCustom: false
    homeCustomLocation: classpath=markdown/home.md
    enableSearch: false
    enableDynamicParameter: true
    enableDebug: true
    enableOpenApi: false
    enableGroup: true
    #设置页脚
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: 哈哈哈哈









